apiVersion: v1
kind: Service
metadata:
  name: back-service
spec:
  selector:
    solution: laboratorio
    part: back
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer